In [1]:
import os
import numpy as np
import pandas as pd
import datetime as dt

In [2]:
FILE = os.path.join('dataset','shoes.csv')

In [3]:
df = pd.read_csv(FILE, index_col=False)
df

,Order Date,Brand,Sneaker Name,Sale Price,Retail Price,Release Date,Shoe Size,Buyer Region
0,9/1/17,Yeezy,Adidas-Yeezy-Boost-350-Low-V2-Beluga,"$1,097",$220,9/24/16,11.0,California
1,9/1/17,Yeezy,Adidas-Yeezy-Boost-350-V2-Core-Black-Copper,$685,$220,11/23/16,11.0,California
2,9/1/17,Yeezy,Adidas-Yeezy-Boost-350-V2-Core-Black-Green,$690,$220,11/23/16,11.0,California
3,9/1/17,Yeezy,Adidas-Yeezy-Boost-350-V2-Core-Black-Red,"$1,075",$220,11/23/16,11.5,Kentucky
4,9/1/17,Yeezy,Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017,$828,$220,2/11/17,11.0,Rhode Island
...,...,...,...,...,...,...,...,...
99951,2/13/19,Yeezy,adidas-Yeezy-Boost-350-V2-Static-Reflective,$565,$220,12/26/18,8.0,Oregon
99952,2/13/19,Yeezy,adidas-Yeezy-Boost-350-V2-Static-Reflective,$598,$220,12/26/18,8.5,California
99953,2/13/19,Yeezy,adidas-Yeezy-Boost-350-V2-Static-Reflective,$605,$220,12/26/18,5.5,New York
99954,2/13/19,Yeezy,adidas-Yeezy-Boost-350-V2-Static-Reflective,$650,$220,12/26/18,11.0,California
99955,2/13/19,Yeezy,adidas-Yeezy-Boost-350-V2-Static-Reflective,$640,$220,12/26/18,11.5,Texas

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99956 entries, 0 to 99955
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    99956 non-null  object
 1   Brand         99956 non-null  object
 2   Sneaker Name  99956 non-null  object
 3   Sale Price    99956 non-null  object
 4   Retail Price  99956 non-null  object
 5   Release Date  99956 non-null  object
 6   Shoe Size     99956 non-null  float64
 7   Buyer Region  99956 non-null  object
dtypes: float64(1), object(7)
memory usage: 6.1+ MB

In [5]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format="%m/%d/%y")
df['Release Date'] = pd.to_datetime(df['Release Date'], format="%m/%d/%y")
df['Sale Price'] = df['Sale Price'].str.replace('$','').str.replace(',','').astype(dtype='float')
df['Retail Price'] = df['Retail Price'].str.replace('$','').str.replace(',','').astype(dtype='float')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99956 entries, 0 to 99955
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    99956 non-null  datetime64[ns]
 1   Brand         99956 non-null  object
 2   Sneaker Name  99956 non-null  object
 3   Sale Price    99956 non-null  float64
 4   Retail Price  99956 non-null  float64
 5   Release Date  99956 non-null  datetime64[ns]
 6   Shoe Size     99956 non-null  float64
 7   Buyer Region  99956 non-null  object
dtypes: datetime64[ns](2), float64(3), object(3)
memory usage: 6.1+ MB

In [7]:
df['Sneaker Name'] = df['Sneaker Name'].str.lower().str.replace('-',' ')
df['Sneaker Name'].unique()

array(['adidas yeezy boost 350 low v2 beluga',
       'adidas yeezy boost 350 v2 core black copper',
       'adidas yeezy boost 350 v2 core black green',
       'adidas yeezy boost 350 v2 core black red',
       'adidas yeezy boost 350 v2 core black red 2017',
       'adidas yeezy boost 350 v2 core black white',
       'adidas yeezy boost 350 v2 cream white',
       'adidas yeezy boost 350 v2 zebra',
       'adidas yeezy boost 350 low moonrock', 'nike air max 90 off white',
       'nike air presto off white', 'nike air vapormax off white',
       'air jordan 1 retro high off white chicago',
       'nike blazer mid off white',
       'adidas yeezy boost 350 low pirate black 2016',
       'adidas yeezy boost 350 low oxford tan',
       'adidas yeezy boost 350 low turtledove',
       'adidas yeezy boost 350 low pirate black 2015',
       'adidas yeezy boost 350 v2 semi frozen yellow',
       'nike air force 1 low off white', 'nike air max 97 off white',
       'nike air force 1 low virgil abloh off white af100',
       'nike react hyperdunk 2017 flyknit off white',
       'nike zoom fly off white', 'adidas yeezy boost 350 v2 beluga 2pt0',
       'adidas yeezy boost 350 v2 blue tint',
       'nike air vapormax off white 2018',
       'air jordan 1 retro high off white white',
       'nike air vapormax off white black',
       'air jordan 1 retro high off white university blue',
       'nike air presto off white black 2018',
       'nike air presto off white white 2018',
       'nike zoom fly mercurial off white black',
       'nike zoom fly mercurial off white total orange',
       'adidas yeezy boost 350 v2 butter',
       'nike air max 97 off white elemental rose queen',
       'nike blazer mid off white all hallows eve',
       'nike blazer mid off white grim reaper',
       'adidas yeezy boost 350 v2 sesame',
       'nike blazer mid off white wolf grey',
       'nike air max 97 off white menta',
       'nike air max 97 off white black',
       'nike zoom fly off white black silver',
       'nike zoom fly off white pink',
       'nike air force 1 low off white volt',
       'nike air force 1 low off white black white',
       'adidas yeezy boost 350 v2 static',
       'adidas yeezy boost 350 v2 static reflective',
       'nike air max 90 off white black',
       'nike air max 90 off white desert ore'], dtype=object)

In [16]:
def extraer_marca(df, lista_de_marcas):
    for marca in lista_de_marcas:
        if marca in df:
            return marca
    
    return "nike"

lista_de_marcas = ['nike', 'adidas']
df['Marca'] = df['Sneaker Name'].str.lower().apply(extraer_marca, lista_de_marcas=lista_de_marcas)

In [17]:
lista_de_modelos = ["air force 1", "zoom fly", "zoom fly mercurial", "air max 97", 
                    "air max 90", "yeezy boost 350 v2", "blazer mid", "air presto",
                   "air vapormax", "air jordan retro 1 high", "air jordan retro 1 low"]

In [18]:
def extraer_modelo(df, lista_de_modelos):
    # Crear una nueva columna para cada zapatilla y asignar los valores correspondientes
    for modelo in lista_de_modelos:
        df = df.apply(lambda x: modelo if modelo in x else x)

    return df

# Ejemplo de uso
lista_de_modelos = ["air force 1", "zoom fly", "zoom fly mercurial", "air max 97", 
                    "air max 90", "yeezy boost 350 v2", "blazer mid", "air presto",
                   "air vapormax", "air jordan retro 1 high", "air jordan retro 1 low"]
df['Modelo'] = extraer_modelo(df['Sneaker Name'], lista_de_modelos)

In [19]:
def off_white(df, off_white="off white"):
    # Crear una nueva columna para cada zapatilla y asignar los valores correspondientes
    if "off white" in df:
        return "Off-White"

    return None

df['Off-White'] = df['Sneaker Name'].apply(off_white)

In [20]:
df[['Sneaker Name','Marca','Modelo','Off-White']].sample(50)

,Sneaker Name,Marca,Modelo,Off-White
75560,adidas yeezy boost 350 v2 zebra,adidas,yeezy boost 350 v2,None
23387,adidas yeezy boost 350 v2 core black red 2017,adidas,yeezy boost 350 v2,None
66877,adidas yeezy boost 350 v2 cream white,adidas,yeezy boost 350 v2,None
86665,adidas yeezy boost 350 v2 sesame,adidas,yeezy boost 350 v2,None
76800,adidas yeezy boost 350 v2 semi frozen yellow,adidas,yeezy boost 350 v2,None
57428,adidas yeezy boost 350 v2 blue tint,adidas,yeezy boost 350 v2,None
17138,nike air presto off white,nike,air presto,Off-White
52301,nike air vapormax off white 2018,nike,air vapormax,Off-White
48364,adidas yeezy boost 350 v2 butter,adidas,yeezy boost 350 v2,None
86370,adidas yeezy boost 350 v2 butter,adidas,yeezy boost 350 v2,None
28632,air jordan 1 retro high off white university blue,nike,air jordan 1 retro high off white university blue,Off-White
46817,nike air vapormax off white,nike,air vapormax,Off-White
847,adidas yeezy boost 350 v2 zebra,adidas,yeezy boost 350 v2,None
51054,adidas yeezy boost 350 v2 butter,adidas,yeezy boost 350 v2,None
84208,adidas yeezy boost 350 v2 sesame,adidas,yeezy boost 350 v2,None
19717,adidas yeezy boost 350 v2 blue tint,adidas,yeezy boost 350 v2,None
34802,adidas yeezy boost 350 v2 butter,adidas,yeezy boost 350 v2,None
70416,adidas yeezy boost 350 v2 butter,adidas,yeezy boost 350 v2,None
74316,adidas yeezy boost 350 v2 semi frozen yellow,adidas,yeezy boost 350 v2,None
7428,nike air force 1 low off white,nike,air force 1,Off-White
79555,adidas yeezy boost 350 v2 semi frozen yellow,adidas,yeezy boost 350 v2,None
58395,adidas yeezy boost 350 v2 core black red,adidas,yeezy boost 350 v2,None
85497,adidas yeezy boost 350 v2 static,adidas,yeezy boost 350 v2,None
18763,adidas yeezy boost 350 v2 blue tint,adidas,yeezy boost 350 v2,None
71374,adidas yeezy boost 350 v2 zebra,adidas,yeezy boost 350 v2,None
10360,adidas yeezy boost 350 v2 beluga 2pt0,adidas,yeezy boost 350 v2,None
27445,air jordan 1 retro high off white university blue,nike,air jordan 1 retro high off white university blue,Off-White
29476,adidas yeezy boost 350 v2 semi frozen yellow,adidas,yeezy boost 350 v2,None
19268,nike air max 97 off white,nike,air max 97,Off-White
53569,adidas yeezy boost 350 v2 cream white,adidas,yeezy boost 350 v2,None
93040,adidas yeezy boost 350 v2 static reflective,adidas,yeezy boost 350 v2,None
78995,nike air force 1 low off white volt,nike,air force 1,Off-White
7815,adidas yeezy boost 350 v2 beluga 2pt0,adidas,yeezy boost 350 v2,None
30074,adidas yeezy boost 350 v2 blue tint,adidas,yeezy boost 350 v2,None
17120,adidas yeezy boost 350 v2 core black red 2017,adidas,yeezy boost 350 v2,None
15539,adidas yeezy boost 350 v2 beluga 2pt0,adidas,yeezy boost 350 v2,None
85407,adidas yeezy boost 350 v2 static,adidas,yeezy boost 350 v2,None
18404,adidas yeezy boost 350 v2 beluga 2pt0,adidas,yeezy boost 350 v2,None
51393,adidas yeezy boost 350 v2 cream white,adidas,yeezy boost 350 v2,None
79947,adidas yeezy boost 350 v2 static reflective,adidas,yeezy boost 350 v2,None
5320,adidas yeezy boost 350 v2 beluga 2pt0,adidas,yeezy boost 350 v2,None
76591,nike air presto off white black 2018,nike,air presto,Off-White
61389,adidas yeezy boost 350 v2 zebra,adidas,yeezy boost 350 v2,None
79842,nike zoom fly mercurial off white total orange,nike,zoom fly,Off-White
26609,nike air vapormax off white 2018,nike,air vapormax,Off-White
31239,air jordan 1 retro high off white university blue,nike,air jordan 1 retro high off white university blue,Off-White
19746,adidas yeezy boost 350 v2 zebra,adidas,yeezy boost 350 v2,None
10538,adidas yeezy boost 350 v2 blue tint,adidas,yeezy boost 350 v2,None
20725,adidas yeezy boost 350 v2 beluga 2pt0,adidas,yeezy boost 350 v2,None
17056,nike air vapormax off white,nike,air vapormax,Off-White

In [21]:
df[df['Marca'].isna()].sample(50)

ValueError: a must be greater than 0 unless no samples are taken

In [22]:
df['Buyer Region'].str.lower().unique()

array(['california', 'kentucky', 'rhode island', 'michigan', 'new york',
       'kansas', 'florida', 'new jersey', 'texas', 'north carolina',
       'oregon', 'alabama', 'delaware', 'virginia', 'wisconsin',
       'colorado', 'massachusetts', 'pennsylvania', 'louisiana',
       'washington', 'georgia', 'ohio', 'nebraska', 'oklahoma',
       'connecticut', 'missouri', 'south carolina', 'maine', 'illinois',
       'nevada', 'maryland', 'arizona', 'minnesota', 'iowa', 'tennessee',
       'west virginia', 'indiana', 'arkansas', 'alaska', 'wyoming',
       'utah', 'new hampshire', 'vermont', 'district of columbia',
       'hawaii', 'new mexico', 'south dakota', 'mississippi',
       'north dakota', 'idaho', 'montana'], dtype=object)

In [23]:
df

,Order Date,Brand,Sneaker Name,Sale Price,Retail Price,Release Date,Shoe Size,Buyer Region,Marca,Modelo,Off-White
0,2017-09-01,Yeezy,adidas yeezy boost 350 low v2 beluga,1097.0,220.0,2016-09-24,11.0,California,adidas,adidas yeezy boost 350 low v2 beluga,None
1,2017-09-01,Yeezy,adidas yeezy boost 350 v2 core black copper,685.0,220.0,2016-11-23,11.0,California,adidas,yeezy boost 350 v2,None
2,2017-09-01,Yeezy,adidas yeezy boost 350 v2 core black green,690.0,220.0,2016-11-23,11.0,California,adidas,yeezy boost 350 v2,None
3,2017-09-01,Yeezy,adidas yeezy boost 350 v2 core black red,1075.0,220.0,2016-11-23,11.5,Kentucky,adidas,yeezy boost 350 v2,None
4,2017-09-01,Yeezy,adidas yeezy boost 350 v2 core black red 2017,828.0,220.0,2017-02-11,11.0,Rhode Island,adidas,yeezy boost 350 v2,None
...,...,...,...,...,...,...,...,...,...,...,...
99951,2019-02-13,Yeezy,adidas yeezy boost 350 v2 static reflective,565.0,220.0,2018-12-26,8.0,Oregon,adidas,yeezy boost 350 v2,None
99952,2019-02-13,Yeezy,adidas yeezy boost 350 v2 static reflective,598.0,220.0,2018-12-26,8.5,California,adidas,yeezy boost 350 v2,None
99953,2019-02-13,Yeezy,adidas yeezy boost 350 v2 static reflective,605.0,220.0,2018-12-26,5.5,New York,adidas,yeezy boost 350 v2,None
99954,2019-02-13,Yeezy,adidas yeezy boost 350 v2 static reflective,650.0,220.0,2018-12-26,11.0,California,adidas,yeezy boost 350 v2,None
99955,2019-02-13,Yeezy,adidas yeezy boost 350 v2 static reflective,640.0,220.0,2018-12-26,11.5,Texas,adidas,yeezy boost 350 v2,None